In [4]:
import numpy as np

In [5]:
np.random.seed(0)  # seed for reproducibility
A = np.random.randint(0 , 10, [5,5])  # 2D array
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

Méthode ndarray

In [6]:
A.argmin(axis=0)

array([0, 0, 0, 1, 2])

In [7]:
np.log(A)

/tmp/ipykernel_47952/2475394391.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(A)


array([[1.60943791,       -inf, 1.09861229, 1.09861229, 1.94591015],
       [2.19722458, 1.09861229, 1.60943791, 0.69314718, 1.38629436],
       [1.94591015, 1.79175947, 2.07944154, 2.07944154, 0.        ],
       [1.79175947, 1.94591015, 1.94591015, 2.07944154, 0.        ],
       [1.60943791, 2.19722458, 2.07944154, 2.19722458, 1.38629436]])

# Statistiques


In [8]:
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [9]:
A.mean()

5.4

In [10]:
A.std()

2.6683328128252666

In [11]:
A.var()

7.12

In [12]:
print(A)
np.corrcoef(A)[0,1]

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]


0.39741306906256163

In [13]:
values, counts = np.unique(A, return_counts=True)

In [14]:
for i,j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} : {j} fois')

valeur 0 : 1 fois
valeur 2 : 1 fois
valeur 1 : 2 fois
valeur 4 : 2 fois
valeur 6 : 2 fois
valeur 3 : 3 fois
valeur 5 : 3 fois
valeur 9 : 3 fois
valeur 7 : 4 fois
valeur 8 : 4 fois


# Nan correction

In [15]:
A = np.random.randn(5,5)
A[0,2] = np.nan
A[4,3] = np.nan
A

array([[ 0.44386323,  0.33367433,         nan, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,         nan, -0.38732682]])

In [16]:
np.nanstd(A)

1.1017518326683546

In [17]:
np.isnan(A).sum()/ A.size # pourcentage de valeurs manquantes

0.08

Booleen Indexing

In [18]:
A[np.isnan(A)] = 0
A

array([[ 0.44386323,  0.33367433,  0.        , -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  0.        , -0.38732682]])

# Algebre lineaire

In [19]:
A = np.ones((2,3))
B = np.ones((3,2))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [22]:
B.dot(A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [23]:
A = np.array([[-2 , 7],
             [2 , 8]])
B = np.array([[3 , 5],
             [-4 ,-8]])
A.dot(B)

array([[-34, -66],
       [-26, -54]])

In [24]:
A = np.random.randint(0 , 10, [3,3])
A

array([[3, 5, 9],
       [4, 4, 6],
       [4, 4, 3]])

In [25]:
np.linalg.pinv(A)

array([[-5.00000000e-01,  8.75000000e-01, -2.50000000e-01],
       [ 5.00000000e-01, -1.12500000e+00,  7.50000000e-01],
       [-1.18188862e-16,  3.33333333e-01, -3.33333333e-01]])

In [26]:
np.linalg.eig(A)

(array([13.58872344, -3.        , -0.58872344]),
 array([[-6.70561268e-01, -8.32050294e-01,  6.04408531e-01],
        [-5.73889829e-01,  1.85511715e-16, -7.73940635e-01],
        [-4.70104297e-01,  5.54700196e-01,  1.88960901e-01]]))

Exercice

In [27]:
np.random.seed(0)  # seed for reproducibility
A = np.random.randint(0 , 100, [10,5])  # 2D array
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [28]:
# Calculer la moyenne de chaque colonne
col_means = np.mean(A, axis=0)

# Soustraire la moyenne de chaque colonne de A
A_centered = A - col_means

# Calculer l'écart-type de chaque colonne
col_stds = np.std(A_centered, axis=0)

# Diviser chaque colonne de A_centered par l'écart-type de cette colonne
A_standardized = A_centered / col_stds

In [29]:
A_standardized

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [31]:
A_standardized.mean(axis = 0)

array([-2.22044605e-17, -4.44089210e-17,  0.00000000e+00, -1.22124533e-16,
       -4.44089210e-17])

In [32]:
A_standardized.std(axis = 0)

array([1., 1., 1., 1., 1.])