In [4]:
import numpy as np

In [5]:
A = np.array([1, 2, 3])
A.shape

(3,)

In [6]:
B = np.ones((3,4))
type(B.shape)

tuple

In [7]:
C = np.ones((3,4))
C.size

12

In [8]:
D = np.full((2,3), 9)
D

array([[9, 9, 9],
       [9, 9, 9]])

In [9]:
np.random.seed(2222223)
np.random.randn(3,4)

array([[ 0.46289935,  0.69463649, -0.43196795,  0.75385057],
       [-0.74398995,  0.61775828, -0.33850959, -0.19364397],
       [-0.33378844, -0.13888212,  1.1657479 ,  1.41089289]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.linspace(0, 10 , 20 , dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [12]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

#  Manipulation

In [13]:
A = np.zeros((3,2))
B = np.ones((3,2))

In [14]:
A

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
C = np.hstack((A,B))
C.shape

(3, 4)

In [17]:
D = np.vstack((A,B))
D.shape

(6, 2)

In [18]:
np.concatenate((A,B), axis=1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [19]:
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
D = D.reshape((3,4))
D.ravel()

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [21]:
A = np.array([1, 2, 3])
A = A.reshape((A.shape[0],1))
A.shape

(3, 1)

In [22]:
A = A.squeeze()
A.shape

(3,)

In [63]:
def initialisation(m, n):
    # m : nombre de lignes
    # n : nombre de colonnes
    A = np.random.randn(m, n)
    # avec une une colonne biais remplie de 1 tout a droite
    A = np.concatenate((A, np.ones((m,1))), axis=1)
    return A

In [65]:
initialisation(4,2)

array([[-2.10696058, -1.414145  ,  1.        ],
       [ 1.68647378, -0.16665224,  1.        ],
       [ 0.23063399, -0.22295036,  1.        ],
       [-1.6730057 , -0.44978998,  1.        ]])